server:
  port: 8020
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user
          predicates:
            - Path=/api/accounts
            - Method=GET
          uri: lb://account

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

